version: "3.7"
services:
  api:
      image: node:18
      container_name: oxinus_task_api
      working_dir: /oxinus-task
      entrypoint: ["/bin/bash", "./scripts/startup.sh"]
      volumes:
          - ./:/oxinus-task
      depends_on:
          - db
      ports:
        - "8080:8080"
  db:
      image: postgres:14
      container_name: oxinus_task_db
      restart: always
      ports:
          - "5427:5432"
      environment:
          POSTGRES_USER: oxinus-task
          POSTGRES_PASSWORD: password
          POSTGRES_DB: oxinus-task-db
      volumes:
        - ./oxinus-task-db:/var/lib/postgresql/data